[[libpolymake_julia]]
arch = "x86_64"
git-tree-sha1 = "12e040e57c6ea9f8996ffb91f63d3179c9313ecf"
os = "macos"

    [[libpolymake_julia.download]]
    sha256 = "a69038b2356d8b7d3c8f81d31a557d8ef3038462ab73a6da71745a9445fe6cbf"
    url = "https://github.com/JuliaBinaryWrappers/libpolymake_julia_jll.jl/releases/download/libpolymake_julia-v0.4.105+0/libpolymake_julia.v0.4.105.x86_64-apple-darwin.tar.gz"
[[libpolymake_julia]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "ed052e20a0e8679067418195e52f8837b27e7a7e"
libc = "glibc"
os = "linux"

    [[libpolymake_julia.download]]
    sha256 = "0d1bac24427a5b078696a350213c961003b8f786fb2327ac0eab5b9c338b2095"
    url = "https://github.com/JuliaBinaryWrappers/libpolymake_julia_jll.jl/releases/download/libpolymake_julia-v0.4.105+0/libpolymake_julia.v0.4.105.x86_64-linux-gnu-cxx11.tar.gz"
