[[libpolymake_julia]]
arch = "x86_64"
git-tree-sha1 = "eb56b54b135704e4eaff64830057fc5d1a11c843"
os = "macos"

    [[libpolymake_julia.download]]
    sha256 = "776de1b1926e7ba6d9f7ef371970fbd7cd5f9a3789771a1ce08bab8718783904"
    url = "https://github.com/JuliaBinaryWrappers/libpolymake_julia_jll.jl/releases/download/libpolymake_julia-v0.4.307+0/libpolymake_julia.v0.4.307.x86_64-apple-darwin.tar.gz"
[[libpolymake_julia]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "a389f2e9a547737a512cb3f1c4e3091c6c0d27ac"
libc = "glibc"
os = "linux"

    [[libpolymake_julia.download]]
    sha256 = "d6ec3a653ec8814430df62ccd570e7e7413bdeef3b47d3fdbcb5f59ad4c4faeb"
    url = "https://github.com/JuliaBinaryWrappers/libpolymake_julia_jll.jl/releases/download/libpolymake_julia-v0.4.307+0/libpolymake_julia.v0.4.307.x86_64-linux-gnu-cxx03.tar.gz"
[[libpolymake_julia]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "3a958ca26d39959dd5a7ec5afb2b5ab5c4190b7a"
libc = "glibc"
os = "linux"

    [[libpolymake_julia.download]]
    sha256 = "3202250fc32631c4ebe961c27767e7000f348d44522fa9da954c921a3aeac85f"
    url = "https://github.com/JuliaBinaryWrappers/libpolymake_julia_jll.jl/releases/download/libpolymake_julia-v0.4.307+0/libpolymake_julia.v0.4.307.x86_64-linux-gnu-cxx11.tar.gz"
