[[libpolymake_julia]]
arch = "x86_64"
git-tree-sha1 = "3ef88db5dca1462e09fd4cffee815b84f87e8fec"
os = "macos"

    [[libpolymake_julia.download]]
    sha256 = "e5c76d212f020c09b1e27106b88ef4995d0dbf7522eb861043410e0f96cbd381"
    url = "https://github.com/JuliaBinaryWrappers/libpolymake_julia_jll.jl/releases/download/libpolymake_julia-v0.3.0+0/libpolymake_julia.v0.3.0.x86_64-apple-darwin.tar.gz"
[[libpolymake_julia]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "77d8b72b47cb3cef58aa61d86370143f1f567e98"
libc = "glibc"
os = "linux"

    [[libpolymake_julia.download]]
    sha256 = "6c31798bb52022d2fb7d1bd548cb48d0b0f10f5c2c9eea56f6d02386b6d85073"
    url = "https://github.com/JuliaBinaryWrappers/libpolymake_julia_jll.jl/releases/download/libpolymake_julia-v0.3.0+0/libpolymake_julia.v0.3.0.x86_64-linux-gnu-cxx11.tar.gz"
