[[libpolymake_julia]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "46f404f64d5373366d6f196ad716b571da2eb2e6"
os = "macos"

    [[libpolymake_julia.download]]
    sha256 = "d8e137517990da3fa44f7dbe39b8eede370bf2e036a648b876afbe89ed89c1c4"
    url = "https://github.com/JuliaBinaryWrappers/libpolymake_julia_jll.jl/releases/download/libpolymake_julia-v0.1.1+0/libpolymake_julia.v0.1.1.x86_64-apple-darwin14-cxx11.tar.gz"
[[libpolymake_julia]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "d9ebad932075ab7bf1e075ebb5841b87c9769749"
libc = "glibc"
os = "linux"

    [[libpolymake_julia.download]]
    sha256 = "ad1feecf7360ea05731d87ca2966dcc901a68333938224b70f8218d516ea068f"
    url = "https://github.com/JuliaBinaryWrappers/libpolymake_julia_jll.jl/releases/download/libpolymake_julia-v0.1.1+0/libpolymake_julia.v0.1.1.x86_64-linux-gnu-cxx11.tar.gz"
