[[libpolymake_julia]]
arch = "x86_64"
git-tree-sha1 = "37d5b1e849863c971d3eec34c29bab7e412a19e8"
os = "macos"

    [[libpolymake_julia.download]]
    sha256 = "616c01aa006e4c521abe1ccfc0fe6203b3ab08964deea51cfd20c7e1b053e40f"
    url = "https://github.com/JuliaBinaryWrappers/libpolymake_julia_jll.jl/releases/download/libpolymake_julia-v0.4.114+0/libpolymake_julia.v0.4.114.x86_64-apple-darwin.tar.gz"
[[libpolymake_julia]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "d4472a25470358396f2022a882299a9a76b30637"
libc = "glibc"
os = "linux"

    [[libpolymake_julia.download]]
    sha256 = "136748aedc25bce4977950e63ae1b83aaf40ecae53e80c47e74926ee2f9e77cb"
    url = "https://github.com/JuliaBinaryWrappers/libpolymake_julia_jll.jl/releases/download/libpolymake_julia-v0.4.114+0/libpolymake_julia.v0.4.114.x86_64-linux-gnu-cxx03.tar.gz"
[[libpolymake_julia]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "77bce9800161be77b2f4983a7522a981da10abab"
libc = "glibc"
os = "linux"

    [[libpolymake_julia.download]]
    sha256 = "d775bdbff06bc0a32effc0ff8dd9bf1866df4b6b8aaaaedefa382e58b5026b4e"
    url = "https://github.com/JuliaBinaryWrappers/libpolymake_julia_jll.jl/releases/download/libpolymake_julia-v0.4.114+0/libpolymake_julia.v0.4.114.x86_64-linux-gnu-cxx11.tar.gz"
