[[libpolymake_julia]]
arch = "x86_64"
git-tree-sha1 = "41fb044d16365972c57329677201a2e616dfbf52"
os = "macos"

    [[libpolymake_julia.download]]
    sha256 = "973e30f8f1e5dc4bccc43942612bd83ff8145b53ec53dde312531dea721a1c8a"
    url = "https://github.com/JuliaBinaryWrappers/libpolymake_julia_jll.jl/releases/download/libpolymake_julia-v0.4.123+0/libpolymake_julia.v0.4.123.x86_64-apple-darwin.tar.gz"
[[libpolymake_julia]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "02367cb583e76a1ca377915cb0a9b14600cb4cbf"
libc = "glibc"
os = "linux"

    [[libpolymake_julia.download]]
    sha256 = "6b5ca1795da03ad82027f2a871da21f98b64d3805f4de07b052e68d7bbc51f44"
    url = "https://github.com/JuliaBinaryWrappers/libpolymake_julia_jll.jl/releases/download/libpolymake_julia-v0.4.123+0/libpolymake_julia.v0.4.123.x86_64-linux-gnu-cxx03.tar.gz"
[[libpolymake_julia]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "d2fa1885d5174397794b1c7fa674d664f0d64b3e"
libc = "glibc"
os = "linux"

    [[libpolymake_julia.download]]
    sha256 = "bb69c77db13102fff91488f03d34be40157304b569a18c33ee5fc8fb3b3e56e9"
    url = "https://github.com/JuliaBinaryWrappers/libpolymake_julia_jll.jl/releases/download/libpolymake_julia-v0.4.123+0/libpolymake_julia.v0.4.123.x86_64-linux-gnu-cxx11.tar.gz"
