[[libpolymake_julia]]
arch = "x86_64"
git-tree-sha1 = "faa76aad3b09c5f97a297151094354f3154ecfc6"
os = "macos"

    [[libpolymake_julia.download]]
    sha256 = "f528eeef46c5ffb0d27eba6f1ba767eec8b795ecfda96712d7cf97bc5fb8e118"
    url = "https://github.com/JuliaBinaryWrappers/libpolymake_julia_jll.jl/releases/download/libpolymake_julia-v0.4.127+0/libpolymake_julia.v0.4.127.x86_64-apple-darwin.tar.gz"
[[libpolymake_julia]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "880a5c2ee9f115d11906e1b9a34ffb32b74058a2"
libc = "glibc"
os = "linux"

    [[libpolymake_julia.download]]
    sha256 = "295644d4f4d286d0258678de3df5a4a59453de4bded773d17ea09431178a21d0"
    url = "https://github.com/JuliaBinaryWrappers/libpolymake_julia_jll.jl/releases/download/libpolymake_julia-v0.4.127+0/libpolymake_julia.v0.4.127.x86_64-linux-gnu-cxx03.tar.gz"
[[libpolymake_julia]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "324e8aaedb06645ed4975432743d51d94bd55696"
libc = "glibc"
os = "linux"

    [[libpolymake_julia.download]]
    sha256 = "c178d492cbbd82ac6837b0638b0e9dcde70d221959918f6e9844e7153d6219d1"
    url = "https://github.com/JuliaBinaryWrappers/libpolymake_julia_jll.jl/releases/download/libpolymake_julia-v0.4.127+0/libpolymake_julia.v0.4.127.x86_64-linux-gnu-cxx11.tar.gz"
