[[libpolymake_julia]]
arch = "x86_64"
git-tree-sha1 = "8e073b28d866f37b9ef3130ae37613b330072c0c"
os = "macos"

    [[libpolymake_julia.download]]
    sha256 = "4e11f55e6ebe01e746272d022130cc5cc49cc09270677188a6875cebed02cf85"
    url = "https://github.com/JuliaBinaryWrappers/libpolymake_julia_jll.jl/releases/download/libpolymake_julia-v0.4.115+0/libpolymake_julia.v0.4.115.x86_64-apple-darwin.tar.gz"
[[libpolymake_julia]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "a004a7a47826e198f264fc63447ce9dfd3d51f92"
libc = "glibc"
os = "linux"

    [[libpolymake_julia.download]]
    sha256 = "98e0c14380c34d9f9b1bb5bb22dc10fe1f63ef319207ffcfbe7c294a80ad261c"
    url = "https://github.com/JuliaBinaryWrappers/libpolymake_julia_jll.jl/releases/download/libpolymake_julia-v0.4.115+0/libpolymake_julia.v0.4.115.x86_64-linux-gnu-cxx03.tar.gz"
[[libpolymake_julia]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "1110546b1bd8f813311ad2cd8859c8fdaa1ab958"
libc = "glibc"
os = "linux"

    [[libpolymake_julia.download]]
    sha256 = "943f60e4a3cbfc4c76ff6cde8cb8196a8095f1026a22d41bb569bdcb4cbddc0d"
    url = "https://github.com/JuliaBinaryWrappers/libpolymake_julia_jll.jl/releases/download/libpolymake_julia-v0.4.115+0/libpolymake_julia.v0.4.115.x86_64-linux-gnu-cxx11.tar.gz"
