[[libpolymake_julia]]
arch = "x86_64"
git-tree-sha1 = "953c9e0347aff95c09f1c94ce54315063283f315"
os = "macos"

    [[libpolymake_julia.download]]
    sha256 = "eea03f067e804f848116f6c9272b3416a3206c3db4f582882b429b2e1110c301"
    url = "https://github.com/JuliaBinaryWrappers/libpolymake_julia_jll.jl/releases/download/libpolymake_julia-v0.2.0+0/libpolymake_julia.v0.2.0.x86_64-apple-darwin.tar.gz"
[[libpolymake_julia]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "954dab6190763512c853daee7dfe255b248f7f47"
libc = "glibc"
os = "linux"

    [[libpolymake_julia.download]]
    sha256 = "a539b8021f6f7ea85c276f38d0c11df66912bb4af40f80da7a99c667d6f19138"
    url = "https://github.com/JuliaBinaryWrappers/libpolymake_julia_jll.jl/releases/download/libpolymake_julia-v0.2.0+0/libpolymake_julia.v0.2.0.x86_64-linux-gnu-cxx11.tar.gz"
